src/AHAS.PO.UI.SITE/Controllers/FeriadoController.cs
using AHAS.PO.SERVICE.APPLICATION.Interfaces;
using AHAS.PO.SERVICE.APPLICATION.ViewModels;
using AHAS.PO.UI.SITE.Helper;
using System.Web.Mvc;

namespace AHAS.PO.UI.SITE.Controllers
{
    public class FeriadoController : Controller
    {
        private readonly IFeriadoAppService _FeriadoAppService;
        private readonly IEstadoAppService _EstadoAppService;
        private readonly IAbrangenciaAppService _AbrangenciaAppService;

        public FeriadoController(IFeriadoAppService feriadoAppService, IAbrangenciaAppService abrangenciaAppService, IEstadoAppService estadoAppService)
        {
            _FeriadoAppService = feriadoAppService;
            _EstadoAppService = estadoAppService;
            _AbrangenciaAppService = abrangenciaAppService;
        }

        // GET: Feriado
        [HttpGet]
        public ActionResult Index()
        {
            return View(_FeriadoAppService.Listar());
        }

        // GET: Feriado/Detalhar/5
        [HttpGet]
        public ActionResult Detalhar(long id)
        {
            FeriadoViewModel viewModel = _FeriadoAppService.Consultar(id);

            if (viewModel == null)
            {
                return HttpNotFound();
            }

            return View(viewModel);
        }

        // GET: Feriado/Adicionar
        [HttpGet]
        public ActionResult Adicionar()
        {
            FeriadoViewModel viewModel = new FeriadoViewModel
            {
                ListaAbrangencia = _AbrangenciaAppService.Listar(),
                ListaEstado = _EstadoAppService.Listar()
            };

            return View(viewModel);
        }

        // POST: Feriado/Adicionar
        [HttpPost]
        public ActionResult Adicionar(FeriadoViewModel viewModel)
        {
            viewModel.ListaAbrangencia = _AbrangenciaAppService.Listar();
            viewModel.ListaEstado = _EstadoAppService.Listar();

            if (ModelState.IsValid)
            {
                viewModel = _FeriadoAppService.Inserir(viewModel);

                if (!viewModel.Sucesso)
                {
                    foreach (var item in viewModel.MensagemValidacao)
                    {
                        ModelState.AddModelError(string.Empty, item);
                    }

                    return View(viewModel);
                }

                foreach (var item in viewModel.MensagemValidacao)
                {
                    TempData["sucesso"] = item;
                }

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // GET: Feriado/Editar/5
        [HttpGet]
        public ActionResult Editar(long id)
        {
            FeriadoViewModel feriadoViewModel = _FeriadoAppService.Consultar(id);

            if (feriadoViewModel == null)
            {
                return HttpNotFound();
            }

            feriadoViewModel.ListaAbrangencia = _AbrangenciaAppService.Listar();
            feriadoViewModel.ListaEstado = _EstadoAppService.Listar();
            
            return View(feriadoViewModel);
        }

        // POST: Feriado/Editar
        [HttpPost]
        public ActionResult Editar(FeriadoViewModel viewModel)
        {
            viewModel.ListaAbrangencia = _AbrangenciaAppService.Listar();
            viewModel.ListaEstado = _EstadoAppService.Listar();

            if (ModelState.IsValid)
            {
                viewModel = _FeriadoAppService.Alterar(viewModel);

                if (!viewModel.Sucesso)
                {
                    foreach (var item in viewModel.MensagemValidacao)
                    {
                        ModelState.AddModelError(string.Empty, item);
                    }

                    return View(viewModel);
                }

                foreach (var item in viewModel.MensagemValidacao)
                {
                    TempData["sucesso"] = item;
                }

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // POST: Feriado/Excluir/5
        [HttpPost]
        public ActionResult Excluir(long id)
        {
            var resultado = new ResultHelper
            {
                Sucess = _FeriadoAppService.Excluir(id)
            };

            return Json(resultado);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _FeriadoAppService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/AHAS.PO.UI.SITE/Controllers/UnidadeController.cs
using AHAS.PO.SERVICE.APPLICATION.Interfaces;
using AHAS.PO.SERVICE.APPLICATION.ViewModels;
using AHAS.PO.UI.SITE.Helper;
using System.Web.Mvc;

namespace AHAS.PO.UI.SITE.Controllers
{
    public class UnidadeController : Controller
    {
        private readonly IUnidadeAppService _UnidadeAppService;

        public UnidadeController(IUnidadeAppService UnidadeAppService)
        {
            _UnidadeAppService = UnidadeAppService;
        }

        // GET: Unidade
        [HttpGet]
        public ActionResult Index()
        {
            return View(_UnidadeAppService.Listar());
        }

        // GET: Unidade/Detalhar/5
        [HttpGet]
        public ActionResult Detalhar(int id)
        {
            UnidadeViewModel viewModel = _UnidadeAppService.Consultar(id);

            if (viewModel == null)
            {
                return HttpNotFound();
            }

            return View(viewModel);
        }

        // GET: Unidade/Adicionar
        [HttpGet]
        public ActionResult Adicionar()
        {
            UnidadeViewModel viewModel = new UnidadeViewModel();

            return View(viewModel);
        }

        // POST: Unidade/Adicionar
        [HttpPost]
        public ActionResult Adicionar(UnidadeViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel = _UnidadeAppService.Inserir(viewModel);

                if (!viewModel.Sucesso)
                {
                    foreach (var item in viewModel.MensagemValidacao)
                    {
                        ModelState.AddModelError(string.Empty, item);
                    }

                    return View(viewModel);
                }

                foreach (var item in viewModel.MensagemValidacao)
                {
                    TempData["sucesso"] = item;
                }

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // GET: Unidade/Editar/5
        [HttpGet]
        public ActionResult Editar(long id)
        {
            UnidadeViewModel viewModel = _UnidadeAppService.Consultar(id);

            if (viewModel == null)
            {
                return HttpNotFound();
            }

            return View(viewModel);
        }

        // POST: Unidade/Editar/5
        [HttpPost]
        public ActionResult Editar(UnidadeViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel = _UnidadeAppService.Alterar(viewModel);

                if (!viewModel.Sucesso)
                {
                    foreach (var item in viewModel.MensagemValidacao)
                    {
                        ModelState.AddModelError(string.Empty, item);
                    }

                    return View(viewModel);
                }

                foreach (var item in viewModel.MensagemValidacao)
                {
                    TempData["sucesso"] = item;
                }

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // POST: Feriado/Excluir/5
        [HttpPost]
        public ActionResult Excluir(long id)
        {
            var resultado = new ResultHelper
            {
                Sucess = _UnidadeAppService.Excluir(id)
            };

            return Json(resultado);
        }
    }
}

src/AHAS.PO.UI.SITE/Views/Shared/_Layout.cshtml
@{
    ViewBag.Title = "Início";
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portal de Obrigações | @ViewBag.Title</title>

    @if (ViewBag.Theme == "black-theme")
    {
        <link type="text/css" href="~/Content/css/shared/layout/black-menu.css" rel="stylesheet" id="black-theme">
    }
    else if (ViewBag.Theme == "gray-theme")
    {
        <link type="text/css" href="~/Content/css/shared/layout/gray-menu.css" rel="stylesheet" id="gray-theme">
    }

    @System.Web.Optimization.Styles.Render("~/bundles/cdn/css/twitter-bootstrap")
    @System.Web.Optimization.Styles.Render("~/bundles/cdn/css/bootstrap-responsive")
    @System.Web.Optimization.Styles.Render("~/bundles/cdn/css/font-awesome-all")
    @System.Web.Optimization.Styles.Render("~/bundles/cdn/css/family-opensans")
    @System.Web.Optimization.Styles.Render("~/bundles/content/css/theme")

    @RenderSection("Styles", false)

</head>
<body>
    <!--MENU SUPERIOR-->
    @Html.Partial("_MenuSuperior")

    <div class="wrapper">
        <div class="container">
            <div class="row">

                <!--MENU LATERAL-->
                @Html.Partial("_MenuLateral")

                <!--CONTEUDO-->
                <div class="span9">
                    <div class="content">
                        @RenderBody()
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--MENU INFERIOR-->
    @Html.Partial("_MenuInferior")

    <!-- Section for main scripts render -->
    @System.Web.Optimization.Scripts.Render("~/bundles/cdn/js/jquery")
    @System.Web.Optimization.Scripts.Render("~/bundles/cdn/js/twitter-bootstrap")
    <script src="~/Content/scripts/shared/theme/page.js" type="text/javascript"></script>

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)

</body>
</html>

src/AHAS.PO.UI.SITE/Views/Shared/_MensagemValidacao.cshtml
@using AHAS.PO.INFRA.CROSS.GLOBALIZING;

@if (ViewData.ModelState[""] != null && ViewData.ModelState[""].Errors.Any())
{
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>@Resources.Global_Validacao_Erro</strong>
        @Html.ValidationSummary(true)
    </div>
}

@if (TempData["sucesso"] != null)
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>@Resources.Global_Validacao_Sucesso</strong>
        <ul><li>@TempData["sucesso"].ToString()</li></ul>    
    </div>
}

src/AHAS.PO.UI.SITE/Views/Shared/_MenuInferior.cshtml
<div class="footer">
    <div class="container">
        <b class="copyright">&copy; 2019 Portal de Obrigações - Alison Horacio </b>Todos os direitos reservados.
    </div>
</div>

src/AHAS.PO.UI.SITE/Views/Shared/_MenuLateral.cshtml
<div class="span3">
    <div class="sidebar">
        <ul class="widget widget-menu unstyled">
            <li class="active">
                <a href="index.html">
                    <i class="menu-icon fas fa-table"></i>Visão Geral Resumida
                </a>
            </li>
            <li>
                <a href="message.html">
                    <i class="menu-icon fas fa-inbox"></i>Mensagens Importantes<b class="label green pull-right">11</b>
                </a>
            </li>
            <li>
                <a href="task.html">
                    <i class="menu-icon fas fa-tasks"></i>Atividades Pendentes<b class="label orange pull-right">19</b>
                </a>
            </li>
        </ul>

        <ul class="widget widget-menu unstyled">
            <li><a href="#"><i class="menu-icon fas fa-clipboard-check"></i>Definir Responsabilidade</a></li>
            <li><a href="#"><i class="menu-icon far fa-calendar-alt"></i>Meus Agendamentos</a></li>
            <li><a href="#"><i class="menu-icon fas fa-clipboard-list"></i>Minhas Responsabilidades </a></li>
            <li><a href="#"><i class="menu-icon fas fa-search"></i>Outros Responsáveis</a></li>
        </ul>

        <ul class="widget widget-menu unstyled">
            <li>
                <a class="collapsed" data-toggle="collapse" href="#togglePages">
                    <i class="menu-icon fas fa-cogs"></i>
                    <i class="fas fa-angle-down pull-right"></i>
                    <i class="fas fa-angle-up pull-right"></i>
                    Manutenção
                </a>
                <ul id="togglePages" class="collapse unstyled">
                    <li><a href="@Url.Action("Index", "Feriado")"><i class="menu-icon icon-gift"></i>Feriados</a></li>
                    <li><a href="#"><i class="menu-icon icon-file"></i>Documentos</a></li>
                    <li><a href="@Url.Action("Index", "Unidade")"><i class="menu-icon icon-briefcase"></i>Unidades</a></li>
                    <li><a href="#"><i class="menu-icon icon-user"></i>Usuários</a></li>
                </ul>
            </li>
            <li><a href="#"><i class="menu-icon fas fa-sign-out-alt"></i>Efetuar Logout</a></li>
        </ul>
    </div>
</div>

src/AHAS.PO.UI.SITE/Views/Shared/_MenuSuperior.cshtml
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                <i class="fas fa-bars shaded"></i>
            </a>

            <a class="brand" href="@Url.Action("Index", "Home")">Portal de Obrigações</a>

            <div class="nav-collapse collapse navbar-inverse-collapse">
                <ul class="nav pull-right">

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Opções Gerais
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="nav-header">Personalização</li>
                            <li><a href="#" onclick="setTheme('gray-theme')"><i class="fas fa-palette"></i>&nbsp;&nbsp;Cores do Menu</a></li>
                            <li><a href="#"><i class="far fa-image"></i>&nbsp;&nbsp;Plano de Fundo</a></li>
                        </ul>
                    </li>

                    <li><a href="#">Ajuda </a></li>

                    <li class="nav-user dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="~/Content/img/noun_User_17241.png" class="nav-avatar" />
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><i class="fas fa-id-card-alt"></i>&nbsp;&nbsp;Meu Perfil</a></li>
                            <li><a href="#"><i class="far fa-address-card"></i>&nbsp;&nbsp;Dados Básicos</a></li>
                            <li><a href="#"><i class="fas fa-cog"></i>&nbsp;&nbsp;Configurações da Conta</a></li>
                            <li class="divider"></li>
                            <li><a href="#"><i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Logout</a></li>
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</div>